-- MySQL Script generated by MySQL Workbench
-- 03/03/17 09:46:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controle_estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controle_estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controle_estoque` DEFAULT CHARACTER SET utf8 ;
USE `controle_estoque` ;

-- -----------------------------------------------------
-- Table `controle_estoque`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(11) NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nomeLoja` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Departamento` (
  `codDepartamento` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Categoria` (
  `codCategoria` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Produto` (
  `codProduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `codCategoria` INT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`codProduto`),
  INDEX `codCategoria_idx` (`codCategoria` ASC),
  CONSTRAINT `codCategoria`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `controle_estoque`.`Categoria` (`codCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(11) NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `idDepartamento` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idDepartamento_idx` (`idDepartamento` ASC),
  CONSTRAINT `idDepartamento`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `controle_estoque`.`Departamento` (`codDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Saida` (
  `codSaida` INT NOT NULL,
  `codFuncionario` INT NOT NULL,
  `dataSaida` DATE NOT NULL,
  PRIMARY KEY (`codSaida`),
  INDEX `codFuncionario_idx` (`codFuncionario` ASC),
  CONSTRAINT `codFuncionario`
    FOREIGN KEY (`codFuncionario`)
    REFERENCES `controle_estoque`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`Pedido` (
  `codPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `codFornecedor` INT NOT NULL,
  PRIMARY KEY (`codPedido`),
  INDEX `codFornecedor_idx` (`codFornecedor` ASC),
  CONSTRAINT `codFornecedor`
    FOREIGN KEY (`codFornecedor`)
    REFERENCES `controle_estoque`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`PedidosFeitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`PedidosFeitos` (
  `codPedido` INT NOT NULL,
  `codProduto` INT NOT NULL,
  `codPedidosFeitos` INT NOT NULL,
  PRIMARY KEY (`codPedidosFeitos`),
  INDEX `codPedido_idx` (`codPedido` ASC),
  INDEX `codProduto_idx` (`codProduto` ASC),
  CONSTRAINT `codPedido`
    FOREIGN KEY (`codPedido`)
    REFERENCES `controle_estoque`.`Pedido` (`codPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codProduto`
    FOREIGN KEY (`codProduto`)
    REFERENCES `controle_estoque`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controle_estoque`.`SaidaRealizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controle_estoque`.`SaidaRealizada` (
  `codSaidaRealizada` INT NOT NULL,
  `codSaida` INT NOT NULL,
  `codProduto` INT NOT NULL,
  PRIMARY KEY (`codSaidaRealizada`),
  INDEX `codProduto_idx` (`codProduto` ASC),
  INDEX `codSaida_idx` (`codSaida` ASC),
  CONSTRAINT `codProduto`
    FOREIGN KEY (`codProduto`)
    REFERENCES `controle_estoque`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codSaida`
    FOREIGN KEY (`codSaida`)
    REFERENCES `controle_estoque`.`Saida` (`codSaida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO CATEGORIA (DESCRICAO) VALUES ('ELETRÔNICOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('LIMPEZA');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('ALIMENTOS');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('NATURAL');


INSERT INTO DEPARTAMENTO (DESCRICAO) VALUES ('VENDAS');
INSERT INTO DEPARTAMENTO (DESCRICAO) VALUES ('ESTOQUE');
INSERT INTO DEPARTAMENTO (DESCRICAO) VALUES ('CONTABILIDADE');



