-- MySQL Script generated by MySQL Workbench
-- 02/14/17 15:34:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `codPessoa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipoPessoa` INT NULL,
  PRIMARY KEY (`codPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `codDepartamento` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `matricula` INT NOT NULL,
  `departamento` INT NOT NULL,
  `codPessoa` INT NOT NULL,
  INDEX `codPessoa_idx` (`codPessoa` ASC),
  INDEX `codDepartamento_idx` (`departamento` ASC),
  PRIMARY KEY (`codPessoa`),
  CONSTRAINT `codDepartamento`
    FOREIGN KEY (`departamento`)
    REFERENCES `mydb`.`Departamento` (`codDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codPessoa`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `mydb`.`Pessoa` (`codPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `nomeLoja` VARCHAR(45) NOT NULL,
  `codPessoa` INT NOT NULL,
  PRIMARY KEY (`codPessoa`),
  CONSTRAINT `codPessoa`
    FOREIGN KEY (`codPessoa`)
    REFERENCES `mydb`.`Pessoa` (`codPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `codCategoria` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codProduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorUnitario` DOUBLE NOT NULL,
  `codCategoria` INT NULL,
  PRIMARY KEY (`codProduto`),
  INDEX `codCategoria_idx` (`codCategoria` ASC),
  CONSTRAINT `codCategoria`
    FOREIGN KEY (`codCategoria`)
    REFERENCES `mydb`.`Categoria` (`codCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Saida` (
  `codSaida` INT NOT NULL,
  `codFuncionario` INT NOT NULL,
  `dataSaida` DATE NOT NULL,
  PRIMARY KEY (`codSaida`),
  INDEX `codFuncionario_idx` (`codFuncionario` ASC),
  CONSTRAINT `codFuncionario`
    FOREIGN KEY (`codFuncionario`)
    REFERENCES `mydb`.`Funcionario` (`codPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `codPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `codFornecedor` INT NOT NULL,
  PRIMARY KEY (`codPedido`),
  INDEX `codFornecedor_idx` (`codFornecedor` ASC),
  CONSTRAINT `codFornecedor`
    FOREIGN KEY (`codFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`codPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PedidosFeitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PedidosFeitos` (
  `codPedido` INT NOT NULL,
  `codProduto` INT NOT NULL,
  `codPedidosFeitos` INT NOT NULL,
  PRIMARY KEY (`codPedidosFeitos`),
  INDEX `codPedido_idx` (`codPedido` ASC),
  INDEX `codProduto_idx` (`codProduto` ASC),
  CONSTRAINT `codPedido`
    FOREIGN KEY (`codPedido`)
    REFERENCES `mydb`.`Pedido` (`codPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codProduto`
    FOREIGN KEY (`codProduto`)
    REFERENCES `mydb`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SaidaRealizada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SaidaRealizada` (
  `codSaidaRealizada` INT NOT NULL,
  `codSaida` INT NOT NULL,
  `codProduto` INT NOT NULL,
  PRIMARY KEY (`codSaidaRealizada`),
  INDEX `codProduto_idx` (`codProduto` ASC),
  INDEX `codSaida_idx` (`codSaida` ASC),
  CONSTRAINT `codProduto`
    FOREIGN KEY (`codProduto`)
    REFERENCES `mydb`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codSaida`
    FOREIGN KEY (`codSaida`)
    REFERENCES `mydb`.`Saida` (`codSaida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
